### ISSUE TITLE
Reports: Edit button takes us to a strange place

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#37]
What is the purpose of the “edit” button at the top of every page. See screenshots with a Metric Question as the access point to the edit page—a very strange place! Incidentally, I don’t think I have come across this page anywhere else. It seems like maybe the page where you would grant someone an extension on their report deadline. Is this true, but why would it be accessed from every page's Edit button? We're confused!!

![screen shot 2016-02-18 at 2 18 49 pm](https://cloud.githubusercontent.com/assets/17168836/13161268/88ae489e-d651-11e5-9c22-c38a086b6d86.png)
![screen shot 2016-02-18 at 2 19 15 pm](https://cloud.githubusercontent.com/assets/17168836/13161269/88c2bbc6-d651-11e5-8485-6de11a0ea9dd.png)

**Comment by ecsion** [comment]
done

**Comment by mgduke** [comment]
Deepak, we're still seeing the same page appear when we click edit in the Reports/2014-2015 Hershman Fellow Final Report/Metrics Question section. ?

**Comment by mgduke** [comment]
OK, figured it out: PI doesn't see this Edit button. Great! But why do us adminitratorial types see it and what are we supposed to do with the Edit page that appears? It doesn't seem to have any utility to us.
