### ISSUE TITLE
Data Migration: People profile/contact info: Mismatched fields & data

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#40]
When we looked up a student, Emily Roberts, under People/Profile…Info, we note that under User Information/Highest Degree, it says "Ocean Acidification in Mussels," which in the source data was associated with Field of Study (MySQL "degree_field"). Possibly this is limited to students, based on checking several investigator and staff records.

**Comment by ecsion** [comment]
Need more discussion since we don;t have all these fields in the new eSeagrant

**Comment by ecsion** [comment]
fixed

**Comment by mgduke** [comment]
Disagree: in the Roberts example given, the Field of Study field still shows "Ocean Acidification in Mussels". If it helps, the original field, degree_field, is in the MySQL "students" table.

**Comment by ecsion** [comment]
Marucs, Is the field of Study the only issues you see or is there any other issue?

**Comment by ecsion** [comment]
fixed.
