### ISSUE TITLE
Impacts & Accomplishments Issues

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#65]
1. Character limit on title is too short (c’mon Deepak, you know how verbose we are!)

2.	**a**. The Submission Preview (and corresponding PDF output) includes “Description” and “Comments” fields, but in the actual I&A form that an investigator would fill out, these fields do not exist (see 1st screenshot); consequently, these fields only show "None" in the Submission Preview (2nd screenshot). 
        Further, we don’t need both fields—just Comments should suffice as there are definitely data in this field in the old system but we can't even find "Description" in FileMaker!
	**b**. In the Submission Preview, the Relevance, Response and Results fields do not appear whereas they do appear in the actual I&A form.

3. Additional fields are missing in the new system that are in the old system’s I&A section:
	**a**. Partners (web interface and FileMaker; note—dropdown list that shows only the partners selected for the given project report on the Partners page)
	**b**. Primary Focus Area (dropdown list, FileMaker only)
	**c**. Program Draft (text field, FileMaker only), which allowed WSG staff to do “versioning” (i.e., copy investigator’s original text to “Program Draft” field and then edit the other fields).

In addition to these fields, we need the following:
	**a**. Associated Projects field (text)
	**b**. Secondary Focus Area (select multiple options): we need to assign these to individual I&A statements within a project report.
	**c**. Goals (select multiple options): Ideally this would be a picklist that we would populate with options

Finally, we don’t need the PI to see all fields in I&A. Instead, the PI should see:
	Title
	Type
	Relevance, Response, Results, Recap (4 fields)
	Comments

All other fields (described above; e.g., partners, primary focus area) should be visible only to WSG staff (RCs/Admins/?other staff?).

<img width="1287" alt="screen shot 2016-03-01 at 9 27 55 am" src="https://cloud.githubusercontent.com/assets/17168836/13436760/97674c30-df95-11e5-9395-e595d4e40766.png">

<img width="1185" alt="screen shot 2016-03-01 at 9 29 45 am" src="https://cloud.githubusercontent.com/assets/17168836/13436868/2a4928e8-df96-11e5-9452-622935c42950.png">

**Comment by mgduke** [comment]
For Julia Parrish, R/OLWD-1

Project Summary:
http://esg.wsg.washington.edu/index.php?module=Reporting&view=Detail&record=3794&mode=showFullReport&tab_label=Submission%20Preview&tab_label=Report%20Summary

I&A page:
http://esg.wsg.washington.edu/index.php?module=Impacts&view=Detail&record=16140

**Comment by ecsion** [comment]
We need to discuss this one.

**Comment by ecsion** [comment]
opening back

**Comment by ecsion** [comment]
done.

**Comment by mgduke** [comment]
Close but not quite done:

1. Please reverse the field order for Comments and Results (Results should come right after Response.

2. Primary and secondary focus area fields still missing (FileMaker field = focus_area; points to summary_info table).  

3. Related partners still missing (FileMaker field = partner_name; points to rep_partners 2 table).

4. Associated projects still missing (called "Related projects" FileMaker, field = rel_projects; points to summary_info table).

5. Goals, which may be a new field that would be populated by a picklist, so I need to confer with Kate on this because currently "Associated Goals" can be found in the Comments field.

**Comment by mgduke** [comment]
CORRECTION to prior note:
Emend item 1: Please move Recap to appear right after Results, followed by Comments and Program Draft.

Notes about initial requests (first submittal above):
Item 2b:  In the Submission Preview, the Relevance, Response and Results fields **still** do not appear whereas they do appear in the actual I&A form.

If the plan for now is to use the custom form Kate built for Impacts&Accomplishments, then none of the other issues stated above matter. If OTOH the plan is to make the fixed I&A module work in the future, then we need to discuss this, including issues stated in prior comments submitted on this ticket.

We understand the plan is to deal with partners in version 2.0.
